<a href="https://colab.research.google.com/github/lorek/Probability_Course_Labs/blob/main/2026_LAB_kolokwium.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorium z rachunku prawdopodobieństwa
## Kolokwium  

<font face="Rage" size=2  > 28.05.2026 <font>


Czas pracy: 45 minut.

# Instrukcja dla studentów

1. Pracujemy samodzielnie.
2. Można korzystać z wcześniejszych list laboratoryjnych oraz własnych wcześniejszych rozwiązań.
3. Nie korzystamy z ChatGPT, Gemini, Copilota ani podobnych narzędzi.
4. Nie korzystamy z automatycznych podpowiedzi AI generujących kod.
5. Nie wyszukujemy rozwiązań w internecie.
6. W razie problemów technicznych proszę zgłosić się do prowadzącego.

Po zakończeniu pracy należy zapisać plik pod nazwą

```text
Nazwisko_kol.ipynb
```

Na przykład:

```text
Kowalski_kol.ipynb
```

Następnie należy pobrać plik jako notebook `.ipynb` i przesłać go **mailem** do prowadzącego (Pawel.Lorek@math.uni.wroc.pl)

W Google Colab można to zrobić przez:

```text
File -> Download -> Download .ipynb
```

# Przygotowanie środowiska

Poniższą komórkę należy uruchomić na początku. W dalszych zadaniach korzystamy z generatora `rng`.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(31415)

# Zadanie 1. Dwie kostki

Rzucamy dwiema sześciennymi kostkami. Niech $S$ oznacza sumę wyników na obu kostkach.

Wykonaj symulację `N = 10000` rzutów dwiema kostkami i odpowiedz na pytania:

1. Oszacuj prawdopodobieństwo zdarzenia $S \geq 10$.
2. Oszacuj prawdopodobieństwo zdarzenia, że $S$ jest liczbą parzystą.
4. Narysuj wykres (np. slupkowy) słupkowy liczby wystąpień poszczególnych sum.

Przydatne funkcje i operacje: `rng.choice`, `np.sum`, `np.arange`, `plt.bar`.

In [ ]:
N = 10000

# Rzuc N razy dwoma kostkami
rzuty = rng.choice(np.arange(1, 7), size=(N, 2), replace=True)

# Suma rzutow
suma = rzuty.sum(axis=1)

print(rzuty[:10])
print(suma[:10])

[[3 3]
 [1 1]
 [6 6]
 [6 6]
 [2 2]
 [5 6]
 [6 5]
 [4 2]
 [5 5]
 [2 2]]
[ 6  2 12 12  4 11 11  6 10  4]


In [ ]:
# Tutaj wpisz rozwiązanie zadania 1.


# Zadanie 2. Prosty spacer losowy
Rozważamy prosty spacer losowy. W każdym kroku pozycja zmienia się o $1$ albo o $-1$,
każda możliwość z prawdopodobieństwem $1/2$.
Dokładniej: niech $X_1,X_2,\ldots,X_n$ będą niezależnymi zmiennymi losowymi takimi, że
$$
 \mathbb{P}(X_i=-1)=\mathbb{P}(X_i=1)=\frac{1}{2},\quad i=1,2,\ldots,n.
$$
Wówczas spacer losowy $S_k, k=0,\ldots,n$, definiujemy następująco: $S_0=0$ oraz
$$
 S_i=X_1+X_2+\ldots+X_i,\quad i=1,2,\ldots,n.
$$

Wylosuj `num_walks = 50` spacerów losowych długości `n = 200`.
Każdy spacer powinien być zapisany w jednej kolumnie macierzy.

Wykonaj następujące polecenia:

1. Utwórz macierz kroków rozmiaru `(n, num_walks)`, zawierającą wartości `-1` oraz `1`.
2. Na podstawie kroków oblicz trajektorie spacerów losowych.
3. Narysuj na jednym wykresie wszystkie trajektorie.
4. Oszacuj prawdopodobieństwo tego, że w ostatnim kroku spacer losowy ma wartość dodatnią, czyli $\mathbb{P}(S_n>0)$.
5. Policz średnią końcową pozycję spośród `num_walks` spacerów, czyli wyestymuj $\mathbb{E}(S_n)$.

Przydatne funkcje i operacje: `rng.choice`, `np.cumsum`, `plt.plot`, `np.mean`, `np.sum`.

(W funkcji `np.cumsum` trzeba odpowiednio dobrać argument `axis`.)

In [ ]:
n = 100
num_walks = 20

# Wylosuj X_i dla wszystkich błądzeń
kroki = rng.choice([-1, 1], size=(n, num_walks), replace=True)

print(kroki.shape)
print(kroki[:5, :5])

(100, 20)
[[-1  1 -1  1  1]
 [-1  1 -1 -1  1]
 [-1  1  1 -1  1]
 [ 1 -1 -1  1  1]
 [-1 -1  1  1 -1]]


In [ ]:
# Tutaj wpisz rozwiązanie zadania 2.
